export const ErrorCode = {
  // 인증 (AUTH_)
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_GOOGLE_FAILED: 'AUTH_GOOGLE_FAILED',
  AUTH_OAUTH_INVALID_CLIENT: 'AUTH_OAUTH_INVALID_CLIENT',
  AUTH_OAUTH_INVALID_GRANT: 'AUTH_OAUTH_INVALID_GRANT',
  AUTH_OAUTH_INVALID_REDIRECT: 'AUTH_OAUTH_INVALID_REDIRECT',
  AUTH_OAUTH_INVALID_SCOPE: 'AUTH_OAUTH_INVALID_SCOPE',
  AUTH_OAUTH_SESSION_EXPIRED: 'AUTH_OAUTH_SESSION_EXPIRED',

  // 유효성 (VALIDATION_)
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // 리소스 (RESOURCE_)
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_FORBIDDEN: 'RESOURCE_FORBIDDEN',

  // 서버 (SERVER_)
  SERVER_INTERNAL: 'SERVER_INTERNAL',
  SERVER_RATE_LIMITED: 'SERVER_RATE_LIMITED',
} as const;

// RFC 6749 OAuth 에러 코드
export const OAuthErrorCode = {
  INVALID_REQUEST: 'invalid_request',
  INVALID_CLIENT: 'invalid_client',
  INVALID_GRANT: 'invalid_grant',
  ACCESS_DENIED: 'access_denied',
  SERVER_ERROR: 'server_error',
} as const;

export type OAuthErrorCodeType =
  (typeof OAuthErrorCode)[keyof typeof OAuthErrorCode];

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
