export const ErrorCode = {
  // 인증 (AUTH_)
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_REFRESH_INVALID: 'AUTH_REFRESH_INVALID',
  AUTH_GOOGLE_FAILED: 'AUTH_GOOGLE_FAILED',

  // 유효성 (VALIDATION_)
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // 리소스 (RESOURCE_)
  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_FORBIDDEN: 'RESOURCE_FORBIDDEN',

  // 서버 (SERVER_)
  SERVER_INTERNAL: 'SERVER_INTERNAL',
  SERVER_RATE_LIMITED: 'SERVER_RATE_LIMITED',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
